from pyrogram import Client, filters
from pyrogram.types import Message
from core_v1.modul import prefixes, app
from core_v1.modul import modules_help
from core_v1.script import edit_or_reply
import time

@app.on_message(filters.command(["koc", "kocok"], prefixes) & filters.me)
async def kocok(client: Client, message: Message):
    message = await edit_or_reply (message, "8✊===D")
    await message.edit("8=✊==D")
    time.sleep(0.0300)
    await message.edit("8==✊=D")
    time.sleep(0.0300)
    await message.edit("8===✊D")
    time.sleep(0.0300)
    await message.edit("8==✊=D")
    time.sleep(0.0300)
    await message.edit("8=✊==D")
    time.sleep(0.0300)
    await message.edit("8✊===D")
    time.sleep(0.0300)
    await message.edit("8=✊==D")
    time.sleep(0.0300)
    await message.edit("8==✊=D")
    time.sleep(0.0300)
    await message.edit("8===✊D")
    time.sleep(0.0300)
    await message.edit("8==✊=D")
    time.sleep(0.0300)
    await message.edit("8=✊==D")
    time.sleep(0.0300)
    await message.edit("8✊===D")
    time.sleep(0.0300)
    await message.edit("8=✊==D")
    time.sleep(0.0300)
    await message.edit("8==✊=D")
    time.sleep(0.0300)
    await message.edit("8===✊D")
    time.sleep(0.0300)
    await message.edit("8==✊=D")
    time.sleep(0.0300)
    await message.edit("8=✊==D")
    time.sleep(0.0300)
    await message.edit("8===✊D💦")
    time.sleep(0.0300)
    await message.edit("8==✊=D💦💦")
    time.sleep(0.0300)
    await message.edit("8=✊==D💦💦💦")
    time.sleep(0.0300)
    await message.edit("8✊===D💦💦💦💦")
    time.sleep(0.0300)
    await message.edit("8===✊D💦💦💦💦💦")
    time.sleep(0.0300)
    await message.edit("8==✊=D💦💦💦💦💦💦")
    time.sleep(0.0300)
    await message.edit("8=✊==D💦💦💦💦💦💦💦")
    time.sleep(0.0300)
    await message.edit("8✊===D💦💦💦💦💦💦💦💦")
    time.sleep(0.0300)
    await message.edit("8===✊D💦💦💦💦💦💦💦💦💦")
    time.sleep(0.0300)
    await message.edit("8==✊=D💦💦💦💦💦💦💦💦💦💦")
    time.sleep(0.0300)
    await message.edit("8=✊==D That's why it's over?")
    time.sleep(0.0300)
    await message.edit("RIP 😭😭😭😭")

modules_help["koc"] = {
    "koc": "type koc to cum"
}
